name: "thanks-action"
description: "Says thanks when a contributor opens an issue"
author: "with-heart"
runs:
  using: "node12"
  main: "./thanks.js"
inputs:
  thanks-message:
    description: "Say thanks"
    default: "Thanks for opening an issue! ❤️"
